install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')

install.packages("shiny")
install.packages("readxl")
install.packages("tidyxl")
install.packages("janitor")
install.packages("magrittr")
